config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
match 'projects/:project_id/pastes', :to => 'pastes#index'
match 'projects/:project_id/pastes/add/api', :to => 'pastes#api'
match 'projects/:project_id/pastes/add', :to => 'pastes#add', :as => 'paste_add'
match 'projects/:project_id/pastes/:id', :to => 'pastes#show'
match 'projects/:project_id/pastes/:id/raw', :to => 'pastes#raw', :as => 'paste_raw'

app/models/paste.rb
class Paste < ActiveRecord::Base
  unloadable

  def self.purge_old

    @items = Paste.where("accessed_at < :month", {:month => 1.month.ago}).destroy_all


  end

  def self.touch(id)
    item = Paste.find(id)
    item.accessed_at = Time.now
    item.save
  end

end

app/controllers/pastes_controller.rb
# todo: language labels into yml
class PastesController < ApplicationController
  unloadable

  before_filter :load_project
  before_filter :authorize
  before_filter :before_each

  protect_from_forgery :except => [:api]
  accept_api_auth :api

  def index
    @items = Paste.where(:project_id=>@project.id, :user_id=>User.current.id).order("created_at DESC")
  end

  def api
    if request.post?

      if save({ :content => request.body.read })
        url = url_for :controller=> "pastes", :action=> "show", :id=> @item.id
        render :text => url, :content_type => 'text/plain'
      else
        render 500
      end
    end
    return
  end

  def add
    if request.post?

      if save(params[:paste])
        url = url_for :controller=> "pastes", :action=> "show", :id=> @item.id
        redirect_to :action=> 'index', :notice => url
      end

    else
      @item = Paste.new
    end
  end

  def show
    get_item
    render_404 unless @item
  end

  def raw
    get_item
    if @item
      render :text => @item.content, :content_type => 'text/plain'
    else
      render_404
    end
  end

  private
  def get_item
    @item = Paste.where(:id=> params[:id], :project_id=> @project.id)[0]
    Paste.touch(params[:id])
  end

  def before_each
    Paste.purge_old
  end

  def load_project
    @project = Project.find(params[:project_id])
  end

  def save(data)
    @item = Paste.new(data)

    @item.user_id = User.current.id
    @item.project_id = @project.id
    @item.accessed_at = Time.now

    @item.save
  end
end

app/helpers/pastes_helper.rb
module PastesHelper
end

app/views/pastes/add.html.erb
<h2>Add new paste</h2>
<%= form_for @item, :url=> {:action=> 'add'} do |form| %>
    <%= form.text_area :content %></br>
    <%= form.submit %>
<% end %>

app/views/pastes/index.html.erb
<h2>Your pastes  (<%= link_to 'add', paste_add_path({:project_id => params[:project_id]}) %>)</h2>

<% if params[:notice] %>
    <div class="warning"><%= params[:notice] %></div>
<% end %>

<ul>
<% @items.each do |item| %>
      <li>#<%= item.id %> - <%= link_to item.created_at, :controller=> "pastes", :action=> "show", :id=> item.id %>  (<%= link_to 'raw', paste_raw_path({:id => item.id, :project_id => params[:project_id]}) %>)</li>
<% end %>
</ul>

app/views/pastes/raw.html.erb
<%== @item.content %>

app/views/pastes/show.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'default.css', :plugin => 'redmine_pastebin' %>
    <%= javascript_include_tag "highlight.pack.js", :plugin => 'redmine_pastebin' %>
    <script>
        hljs.lineNodes = true;
        hljs.initHighlightingOnLoad();
    </script>
<% end %>

<h2>Paste#<%= @item.id %> (<%= link_to 'raw', paste_raw_path({:id => @item.id, :project_id => params[:project_id]}) %>)</h2>

<p>Created at: <%= @item.created_at %></p>

<pre><code><%= @item.content %></code></pre>